# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site Setting
title: Junteng Liu
name: Junteng Liu
description: First-year PhD candidate at HKUST NLP Group
url: "https://cold64susex.github.io"
baseurl: "/LJT-Homepage"
logo: # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
mast_title: # title to display in the masthead, default '' (use title)
mast_tagline: # tagline to display in the masthead, default '' (use description)

# The gig center (or location)
location: Hong Kong

# Site Author
author:
  name: "Junteng Liu"
  avatar: "/images/bio-photo.jpg"
  bio: "First-year PhD candidate at HKUST NLP Group."
  location: "Hong Kong"
  email: "jliugi@connect.ust.hk"
  twitter_username: "junteng88716710"
  facebook_username:
  github_username: "Vicent0205"
  linkedin_username:
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  orcid:
  researchgate:
  Mastodon:
  arxiv:
  blogger:
  wikipedia:
  acm_id:
  stackoverflow:
  impactstory:
  telephon:
  keybase:
  googlescholar_title:
  im_name:
  reproducibility:
  plus:
  qq:
  weibo:
  douban:
  zhihu:
  lastfm:
  lanyard:
  gpg:
  goodreads:
  medium:
  wechat:
  myspace:
  Flickr:
  flickr:
  vk:
  youtube:
  soundcloud:
  twitch:
  pinterest:
  etsy:
  devianart:
  smash:
  google:
  ycombinator:
  gitlab:
  fivehundredpx:
  instagram:
  tumblr:
  bitbucket:
  disqus:
  spotify:
  steam:
  twitter:
  yelp:
  google_plus:
  comments:

# Site Footer
footer:
  links:
    label: "Label"
    icon: "fa-solid fa-user"
    url: "https://example.com"
    title: "Title"
    email: "jliugi@connect.ust.hk"

# Reading files
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: true
  startings: [html, head, body]

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Other stuff
classes: wide

# Analytics
analytics:
  provider: "false"
  google:
    tracking_id: "your-universal-id"
    anonymize_ip: false
